### ISSUE TITLE
感觉非常好的一个示例应用！不知能否再添加多些示例应用呢？

### ISSUE THREAD

**Issue by winsonet** [woaigmz/flutter_fish#1]
先感谢提供这么好的 Demo，不过可惜的是文档和示例太少了，通过看代码也基本上了解整体架构和使用了，不过其中看到你项目中有一个```ptr_container.dart```感觉好像好强大哦，但苦于没有相关示例，根本不知道如何使用，如果方便的话，可否添加一些这个 widget 的使用示例或者文档说明呢？

谢谢啦！！

**Comment by iloveq** [comment]
感谢您的 issues ，ptr 是个下拉刷新的 widget 但是一直没时间，所以没能完成 。 有空的话我会继续更新的 ：） 感谢关注

**Comment by winsonet** [comment]
好的，谢谢啦！:)
